#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: OpenWrt firmware immortalwrtARM 360t7

on:
  workflow_dispatch:
  schedule:
    - cron: 0 21 * * 5

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        
    - name: Clone source code
      env: 
        REPO_URL: https://github.com/padavanonly/immortalwrtARM
        REPO_BRANCH: mt7981
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
       
    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: Configuration Customization
      env:
        CONFIG_FILE: 'config/T7.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
        
    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s
        
    - name: 检查可用容量
      if: (!cancelled())
      run: df -hT

    - name: 组织文件
      run: |
        cd openwrt/bin/targets/*/*
        tar -cvf package.tar packages
        rm -rf feeds.buildinfo
        rm -rf *kernel*
        rm -rf *.manifest
        rm -rf *.tar.bz2
        rm -rf sha256sums
        rm -rf version.buildinfo
        sleep 2
        mv immortalwrt-mediatek-mt7981-mt7981-360-t7-108M-squashfs-sysupgrade.bin 360T7-padavanonly-108M-sysupgrade.bin
        mv immortalwrt-mediatek-mt7981-mt7981-360-t7-108M-squashfs-factory.bin 360T7-padavanonly-108M-factory.bin
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT 
        
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt firmware immortalwrtARM 360t7
        path: openwrt/bin
